#!/usr/bin/env node
/**
 * Reads .env and writes the values into the extension:
 *   - manifest.json      site URL (matches + host_permissions)
 *   - src/config.js      runtime numbers for the controller
 *
 * Chrome cannot read .env itself, so this runs once per settings change.
 */
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;

const FIELDS = [
  { key: 'SITE_URL', type: 'url' },
  { key: 'MAX_ATTEMPTS', type: 'count' },
  { key: 'RETRY_INTERVAL_SECONDS', type: 'count' },
  { key: 'RESPONSE_TIMEOUT_SECONDS', type: 'count' }
];

function parseEnv(text) {
  const values = {};
  for (const raw of text.split('\n')) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;

    const separator = line.indexOf('=');
    if (separator === -1) continue;

    const key = line.slice(0, separator).trim();
    const value = line.slice(separator + 1).trim().replace(/^["']|["']$/g, '');
    if (key) values[key] = value;
  }
  return values;
}

function validate(values) {
  const problems = [];
  const config = {};

  for (const { key, type } of FIELDS) {
    const value = values[key];

    if (value === undefined || value === '') {
      problems.push(`${key} is missing.`);
      continue;
    }

    if (type === 'url') {
      if (!/^https?:\/\/\S+$/.test(value)) {
        problems.push(`${key} must start with http:// or https:// (got "${value}").`);
      } else if (value.includes('REPLACE-ME')) {
        problems.push(`${key} is still the placeholder. Put your real site URL in .env.`);
      } else {
        config[key] = value.endsWith('*') ? value : `${value.replace(/\/$/, '')}/*`;
      }
      continue;
    }

    const number = Number(value);
    if (!Number.isInteger(number) || number < 1) {
      problems.push(`${key} must be a whole number of at least 1 (got "${value}").`);
    } else {
      config[key] = number;
    }
  }

  if (problems.length) {
    throw new Error(`Problems in .env:\n  - ${problems.join('\n  - ')}`);
  }
  return config;
}

function readConfig(envPath) {
  if (!fs.existsSync(envPath)) {
    throw new Error('No .env found. Copy .env.example to .env and fill it in.');
  }
  return validate(parseEnv(fs.readFileSync(envPath, 'utf8')));
}

function writeManifest(config) {
  const file = path.join(ROOT, 'manifest.json');
  const manifest = JSON.parse(fs.readFileSync(file, 'utf8'));

  manifest.host_permissions = [config.SITE_URL];
  for (const script of manifest.content_scripts) {
    script.matches = [config.SITE_URL];
  }

  fs.writeFileSync(file, `${JSON.stringify(manifest, null, 2)}\n`);
}

function writeRuntimeConfig(config) {
  const body = `// Generated by build.js from .env. Do not edit by hand.
globalThis.QUEUE_REFRESH_CONFIG = {
  maxAttempts: ${config.MAX_ATTEMPTS},
  retryDelayMs: ${config.RETRY_INTERVAL_SECONDS * 1000},
  responseTimeoutMs: ${config.RESPONSE_TIMEOUT_SECONDS * 1000}
};
`;
  fs.writeFileSync(path.join(ROOT, 'src', 'config.js'), body);
}

function main() {
  const config = readConfig(path.join(ROOT, '.env'));
  writeManifest(config);
  writeRuntimeConfig(config);

  console.log('Extension updated from .env:');
  console.log(`  site              ${config.SITE_URL}`);
  console.log(`  max attempts      ${config.MAX_ATTEMPTS}`);
  console.log(`  retry interval    ${config.RETRY_INTERVAL_SECONDS}s`);
  console.log(`  response timeout  ${config.RESPONSE_TIMEOUT_SECONDS}s`);
  console.log('\nNow press the reload arrow on the extension in chrome://extensions.');
}

if (require.main === module) {
  try {
    main();
  } catch (error) {
    console.error(error.message);
    process.exit(1);
  }
}

module.exports = { parseEnv, validate, readConfig };
